### ISSUE TITLE
feature request: preview-middleware

### ISSUE THREAD

**Issue by heimwege** [ui5-community/generator-ui5-ts-app#35]
Hi guys,

how about using the [preview middleware](https://www.npmjs.com/package/@sap-ux/preview-middleware) to get rid of the test glue code?

Using this config in the ui5*.yaml (further configuration w.r.t paths, testfile name patterns, etc. is possible)

```
  - name: preview-middleware
    afterMiddleware: compression
    configuration:
      test:
        - framework: QUnit
        - framework: OPA5
        - framework: Testsuite
```

makes the following files superfluous:
- /test/testsuite.qunit.html
- /test/testsuite.qunit.js
- /integration/opaTests.qunit.html
- /integration/opaTests.qunit.js
- /unit/unitTests.qunit.html
- /unit/unitTests.qunit.js

Having this glue code centrally managed could be quite helpful in case the test recommended setup changes (e.g. because `resources/sap/ui/test/starter/createSuite.js` should be used).

Using this middleware might not only be relevant for the ts app generator but for other generators as well.
